|Array |  Tensor | Maths | 
|:-----|:--------|:------| 
| 0D | rank 0 | scalar |
| 1D | rank 1 | vector |
| 2D | rank 2 | matrix |
| 3D | rank 3 | - |

The table shows correspondences between array, tensor and mathematical language. Arrays are any computational implementation of vectors, matrices and higher dimensional structures, and tensors are the special Numpy construction. The terms are interchangeable, however, and tensors also occur in maths. So we shall use the terms fairly freely. A 1D array is a rank 1 tensor is a vector and so on. 

Tensor rank/dimension is the number of axes

Tensor **shape** is the number of elements along each axis i.e. the length of each axis

The type of a tensor is the data type of the contained data - `float32`, `uint8`...

Tensor rank/dimension is the number of axes. Tensor **shape** is the number of elements along each axis i.e. the length of each axis. The type of a tensor is the data type of the contained data - `float32`, `uint8`...

In [1]:
# the shape of a scalar
import numpy as np
x = np.array(93)
print(x, '\t', x.shape)

93 	 ()


Unsurprisingly, the shape of a scalar is nothing at all.

In [2]:
# the shape of a vector
x = np.array([1, 2, 3])
print(x, '\t', x.shape)

[1 2 3] 	 (3,)


Tensor shape is a Python tuple, and since Python tuples are values separated by commas, a vector has shape 'length comma', which looks odd but is correct. (3 without a comma would indicate a normal value, not a tuple.)

In [3]:
# the shape of a 2D array
x = np.array([[1, 2, 3], [4, 5, 5]])
print(x, '\t', x.shape)

[[1 2 3]
 [4 5 5]] 	 (2, 3)


Two rows and three columns: shape (2, 3)

In [4]:
# the shape of a 3D array
x = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(x, '\t', x.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]] 	 (3, 2, 2)


Three two by two matrices or arrays: shape (3, 2, 2).

|                        |        |
|-----------------------:|:-------|
| multidimensional array | tensor |
| dimension              | axis   |
| number of dimensions   | rank  
| length | number of elements in a 1D array/along a tensor axis |
| size | number of matrix rows and cols 
| shape | lengths of each tensor axis |

Here is another table of jargon explanation. The important new concepts are 'axis', 'rank' and 'shape' and you should make sure you understand these terms. 

In [5]:
# the rank, shape and type of MNIST images
# load images
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

For example, the MNIST image tensor have

In [6]:
# rank
train_images.ndim

3

rank

In [7]:
# shape
train_images.shape

(60000, 28, 28)

shape

In [8]:
# data type
train_images.dtype

dtype('uint8')

and type