Data in a 2D array is accessed with two indices

- analogous to mathematical matrices

- the size of a matrix is the number of rows and columns

Data in a 2D array is accessed with two indices. 2D arrays are analogous to mathematical matrices - the 'size' of a matrix is the number of rows and columns.

\begin{eqnarray}
x = \begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 
\end{pmatrix}
\end{eqnarray}

A matrix of size 2 x 3

- two rows and three columns

A matrix of size 2 by 3 - two rows and three columns

In [1]:
# python 2D array
x = [[1, 2, 3], 
     [4, 5, 6]]
print('x: ', x, '\n')

# an array of vectors
a = [1, 2, 3]
b = [4, 5, 6]
print('a:', a)
print('b:', b)
print('[a, b]: ', [a, b]) 

x:  [[1, 2, 3], [4, 5, 6]] 

a: [1, 2, 3]
b: [4, 5, 6]
[a, b]:  [[1, 2, 3], [4, 5, 6]]


Python 2D arrays are lists of lists. `x` is constructed by nesting lists directly, or by creating and then stacking two lists `a` and `b`.

In [2]:
# numpy 2D array
import numpy as np
x = np.array([[1, 2, 3], 
              [4, 5, 6]])

print('x: \n', x, '\trank:', x.ndim, '\n') 
print('x[0]:', x[0], '\trank:', x[0].ndim)

x: 
 [[1 2 3]
 [4 5 6]] 	rank: 2 

x[0]: [1 2 3] 	rank: 1


Rank 2 tensor formation is similar in Numpy - nested lists - except the Python structure is passed to `np.array`. `x[0]` and `x[1]` retreive matrix rows as rank 1 tensors or vectors. 

In [3]:
# a rank 3 tensor
x = np.array([[[1, 2], 
               [3, 4]],
              
              [[5, 6], 
               [7, 8]],
              
              [[9, 10], 
               [11, 12]]])

print('x:\n', x, '\trank:', x.ndim) 

x:
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]] 	rank: 3


Creating rank 3 tensors is a little hairy - difficult to get all the brackets matched. But the idea is clear: a vector of 2D arrays. 

In [4]:
# one index selects a 2D array
print('x: \n', x, '\n\n') 
print('x[2]:\n', x[2], '\trank:', x[2].ndim)

x: 
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]] 


x[2]:
 [[ 9 10]
 [11 12]] 	rank: 2


One index selects a 2D array.

In [5]:
# two indices select a vector
print('x: \n', x, '\n\n', 
       'x[2][0]: ', x[2][0], '\trank:', x[2][0].ndim)

x: 
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]] 

 x[2][0]:  [ 9 10] 	rank: 1


Two indices select a vector.

In [6]:
# three indices select a scalar - a single element
print('x: \n', x, '\n\n'
      'x[2][0][1]:', x[2][0][1])

x: 
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]] 

x[2][0][1]: 10


 Three indices select a scalar - a single element.