Tensors elements can be redistributed in an operation known as **reshaping**

- the original (60000, 28, 28) MNIST data was reshaped
- `train_images = train_images.reshape((60000, 28 * 28))`

Tensors elements can be redistributed in an operation not surprisingly known as 'reshaping'. The original MNIST data was reshaped from (60000, 28, 28) to (60000, 784) by calling `reshape`.
- `train_images = train_images.reshape((60000, 28 * 28))`

In [1]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6]])
print(x, '\t', x.shape)

[[1 2]
 [3 4]
 [5 6]] 	 (3, 2)


We look at the reshaping of a (3, 2) tensor - a matrix with 3 rows and two columns.

In [2]:
x = x.reshape(6, 1)
print(x)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


The six elements of the 3 by 2 array are reshaped to comlun vector of 6 rows.

**Transposition** is another possibility

'Transposition' is another reshaping possibility.

In [3]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x = x.transpose()
print(x, '\t', x.shape)

[[1 3 5]
 [2 4 6]] 	 (2, 3)


Transposition switches 2D rows and columns. The Numpy manual explains more complicated transpositions of tensor axes.